name: Docs Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up bash
        run: sudo apt-get update && sudo apt-get install -y git jq

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Run changelog check and comment on PR if necessary
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/scripts/check_and_comment.sh
